services:
  database:
    container_name: db
    image: postgres:14.2-alpine3.15
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432